### PR TITLE
all dp related questions

### PR DESCRIPTION
**Pull request by Abhibhab**

### CODE REVIEW

**Review by HemangJoshi — COMMENTED** [review]
great work @Abhibhab

**Comment by HemangJoshi** [comment]
can you also provide the actual problem statements for the programs so that they can be referred to @Abhibhab

**Comment by Abhibhab** [comment]
okay sir working on it
but sir why it is not accepted under hacktoberfest lebel

**Comment by HemangJoshi** [comment]
the files are being reviewed 
as there many files the process will take some time
but once the prcess is completed and approved the label will be added

**Pull request merged**
